channels:
  - conda-forge

dependencies:
  - jupyterlab
  - ipympl
  - jupyter_bokeh

  - python =3.12
  - emsarray =0.9
  - numpy =2.2
  - xarray =2025.01
  - bokeh =3.6
  - netCDF4 =1.7
  - ffmpeg
  - scipy
  - cartopy~=0.24.0
  - owslib~=0.33.0
  - pillow~=11.1.0
